labels:
  - name: bug
    labeled:
      issue:
        body: |
          We do not accept bug on this repo. Please submit your issue on this repo : https://github.com/homebridge-eufy-security/plugin/issues/new/choose, thanks. If you have any questions, please feel free to contact us.
  - name: enhancement
    labeled:
      issue:
        body: |
          We do not accept enhancement on this repo. Please submit your enhancement on this repo : https://github.com/homebridge-eufy-security/plugin/issues/new/choose, thanks. If you have any questions, please feel free to contact us.
