blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/homebridge-eufy-security/plugin/issues/new?assignees=&labels=bug&template=bug-report.yml&title=%5BBug%5D%3A+
    about: File a bug report
  - name: Feature Request
    url: https://github.com/homebridge-eufy-security/plugin/issues/new?assignees=&labels=enhancement&template=feature-request.yml&title=%5Benhancement%5D%3A+
    about: Suggest an idea for this project
  - name: Discord
    url: https://discord.gg/hZqqTfjzet
    about: The Homebridge Discord Community - Issue must be filled before reaching us!
