name: Close Pull Request

on:
  pull_request_target:
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "We do not accept PRs on this repo. Please submit your PR through the dev or beta branch on this repo : https://github.com/homebridge-eufy-security/plugin/pulls, thanks. If you have any questions, please feel free to contact us."
