name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '15 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          exempt-all-pr-assignees: true
          close-issue-message: 'We do not accept issue on this repo. Please submit your issue on this repo : https://github.com/homebridge-eufy-security/plugin/issues, thanks. If you have any questions, please feel free to contact us.'
          close-pr-message: 'We do not accept PR on this repo. Please submit your issue on this repo : https://github.com/homebridge-eufy-security/plugin/pulls, thanks. If you have any questions, please feel free to contact us.'
          days-before-close: 0
          days-before-pr-close: 0
